server:
  port: 8082
spring:
  main.allow-bean-definition-overriding: true

dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://175.178.29.54:2181
    protocol:
      id: dubbo
      name: dubbo
      port: 20880
